[tool.black]
line-length = 100
target-version = ["py38", "py39", "py310"]
include = '\.pyi?$'


[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
known_local_folder=['config',]
